---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirrostestvm
  namespace: cirrosvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: cirrostestvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - bridge: {}
              name: cn2-network
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      networks:
        - name: cn2-network
          multus:
            networkName: cirros-nad
      terminationGracePeriodSeconds: 30
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
