---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cirros-nad
  namespace: cirrosvm
  annotations:
    juniper.net/networks: '{
      "ipamV4Subnet": "192.168.10.0/24"
    }'
spec:
  config: '{
    "cniVersion":"0.3.1",
    "name": "cirros-nad",
    "type": "contrail-k8s-cni"
  }'
