---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: blue-vn
  namespace: centosvm
  annotations:
    juniper.net/networks: '{ "ipamV4Subnet": "192.168.40.0/24" }'
  labels:
    vn: red-blue-vn
spec:
  config: '{
    "cniVersion":"0.3.1",
    "name": "blue-vn",
    "type": "contrail-k8s-cni"
  }'
