---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dv-pv0
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  local:
    path: /var/dv/vol1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - workernode01
