---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc1
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
