---
apiVersion: v1
kind: Pod
metadata:
  name: pod02-local-pvc1
spec:
  containers:
  - name: spod02
    imagePullPolicy: IfNotPresent
    image: docker.io/busybox
    command: ["/bin/sh", "-c","while true; do echo 'Pod Writing' >> /var/pv/pv1/demo1 ; sleep 5; done"]
    volumeMounts:
      - mountPath: "/var/pv/pv1"
        name: pod-local-vol1
  volumes:
  - name: pod-local-vol1
    persistentVolumeClaim:
      claimName: local-pvc1
