---
apiVersion: v1
kind: Pod
metadata:
  name: hubpod1
  namespace: ns1-hs
  annotations:
    k8s.v1.cni.cncf.io/networks: vn3-ns1-hs
spec:
  containers:
    - name: hubpod1
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["bash", "-c","while true; do sleep 60s; done"]
      securityContext:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
