---
apiVersion: v1
kind: Namespace
metadata:
  name: same-ns-mmesh
  labels:
    ns: same-ns-mmesh
spec:
  finalizers:
  - kubernetes
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: Subnet
metadata:
  namespace: same-ns-mmesh
  name: subnet1-mmesh
  annotations:
    core.juniper.net/display-name: Subnet1MMesh
    core.juniper.net/description: Subnet represents a block of IP addresses and its configuration.
spec:
  cidr: "172.168.100.0/24"
  defaultGateway: "172.168.100.254"
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: Subnet
metadata:
  namespace: same-ns-mmesh
  name: subnet2-mmesh
  annotations:
    core.juniper.net/display-name: Subnet2MMesh
    core.juniper.net/description: Subnet represents a block of IP addresses and its configuration.
spec:
  cidr: "172.168.110.0/24"
  defaultGateway: "172.168.110.254"
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: VirtualNetwork
metadata:
  namespace: same-ns-mmesh
  name: vn1-mmesh
  annotations:
    core.juniper.net/display-name: VN1-mmesh
    core.juniper.net/description: VirtualNetwork represents.
  labels:
    vn: web
spec:
  v4SubnetReference:
    apiVersion: core.contrail.juniper.net/v1alpha1
    kind: Subnet
    namespace: same-ns-mmesh
    name: subnet1-mmesh
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: VirtualNetwork
metadata:
  namespace: same-ns-mmesh
  name: vn2-mmesh
  annotations:
    core.juniper.net/display-name: VN2-mmesh
    core.juniper.net/description: VirtualNetwork represents.
  labels:
    vn: web
spec:
  v4SubnetReference:
    apiVersion: core.contrail.juniper.net/v1alpha1
    kind: Subnet
    namespace: same-ns-mmesh
    name: subnet2-mmesh
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: VirtualNetworkRouter
metadata:
  namespace: same-ns-mmesh
  name: mvnr01
  annotations:
    core.juniper.net/display-name: mvnr01
  labels:
      vnr: web
spec:
  type: mesh
  virtualNetworkSelector:
    matchLabels:
      vn: web
  import:
    virtualNetworkRouters:
      - virtualNetworkRouterSelector:
          matchLabels:
            vnr: db
        namespaceSelector:
          matchLabels:
            ns: same-ns-mmesh
