---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windowshd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k12-pvc
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: medium
        kubevirt.io/domain: win2k12-pvc
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - bootOrder: 1
              cdrom:
                bus: sata
              name: cdromiso
            - disk:
                bus: virtio
              name: harddrive
            - cdrom:
                bus: sata
              name: virtiocontainerdisk
        machine:
          request: ""
        resources:
          requests:
            memory: 6Gi
      volumes:
        - name: cdromiso
          persistentVolumeClaim:
            claimName: win-pvc
        - name: harddrive
          persistentVolumeClaim:
            claimName: windowshd
        - name: virtiocontainerdisk
          containerDisk:
            image: kubevirt/virtio-container-disk
